name: Sync Labels

on:
  push:
    branches:
      - main  
  workflow_dispatch:  #

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ahmadnassri/action-label-sync@v1
        with:
          repo-token: ${{ secrets.ORG_LABEL_TOKEN }}
          configuration-path: .github/labels.yml
